@startuml
<style>
    participant {
        FontColor White
    }
</style>
!include Style.puml
actor user

participant ":TutorLink" as TL LOGIC_COLOR_5
participant ":Ui" as UI LOGIC_COLOR_6
participant ":Logic" as L LOGIC_COLOR_7
participant ":AppState" as A LOGIC_COLOR_3
participant ":Storage" as S LOGIC_COLOR_4

create TL
user -> TL: start
activate TL
create UI
TL -> UI
activate UI
create A
UI -> A : new AppState
activate A
UI <-- A : appState
deactivate A
create L
UI -> L : new Logic
activate L
UI <-- L : logic
deactivate L
deactivate UI
create L
create S
TL -> S
user -> TL:"delete_student i/A1234567X"
TL -> UI: runApp()
activate UI
UI -> L : execute(line)
activate L
L -> A : deleteStudentByMatricNumber("A1234567X")
activate A
A -> S : saveStudentFile(students)
activate S
S -> S : save to file
activate S
S --> S
deactivate S
A <-- S
deactivate S

L <-- A
deactivate A
UI <-- L : CommandResult
deactivate L
UI -> UI : displayResult
activate UI
UI --> UI
deactivate UI
TL <-- UI
user <-- TL
@enduml