!define LOGIC_COLOR_1 #1A1A1A
!define BOX_COLOR_1 #1A1A1A80

!define LOGIC_COLOR_2 #2C3E50
!define BOX_COLOR_2 #2C3E5080

!define LOGIC_COLOR_3 #8E44AD
!define BOX_COLOR_3 #8E44AD80

!define LOGIC_COLOR_4 #D35400
!define BOX_COLOR_4 #D3540080

!define LOGIC_COLOR_5 #C0392B
!define BOX_COLOR_5 #C0392B80

!define LOGIC_COLOR_6 #2980B9
!define BOX_COLOR_6 #2980B980

!define LOGIC_COLOR_7 #27AE60
!define BOX_COLOR_7 #27AE6080

!define LOGIC_COLOR_8 #F39C12
!define BOX_COLOR_8 #F39C1280

!define LOGIC_COLOR_9 #8E44AD
!define BOX_COLOR_9 #8E44AD80

!define LOGIC_COLOR_10 #34495E
!define BOX_COLOR_10 #34495E80


!define USER_COLOR #000000

skinparam ArrowFontStyle bold
skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle